repos:
  - repo: local
    hooks:
      - id: scan-secrets
        name: Scan secrets
        entry: /usr/bin/env check=whole-history ./scripts/githooks/scan-secrets.sh
        language: script
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-file-format
        name: Check file format
        entry: /usr/bin/env check=branch ./scripts/githooks/check-file-format.sh
        language: script
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-markdown-format
        name: Check Markdown format
        entry: /usr/bin/env check=branch ./scripts/githooks/check-markdown-format.sh
        language: script
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-english-usage
        name: Check English usage
        entry: /usr/bin/env check=branch ./scripts/githooks/check-english-usage.sh
        language: script
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint-terraform
        name: Lint Terraform
        entry: ./scripts/githooks/check-terraform-format.sh
        language: script
        pass_filenames: false
