name: Github Release Created

on:
  release:
    types: ["published"] # Inherits all input defaults

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to main in nonprod AWS Account

    permissions:
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        component: [acct, app]

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      releaseVersion: ${{ github.event.release.tag_name }}
      targetWorkflow: "dispatch-deploy-static-notify-iam-env.yaml"
      targetEnvironment: "main"
      targetAccountGroup: "nhs-notify-iam-nonprod"
      targetComponent: ${{ matrix.component }}
      terraformAction: "apply"
