name: Acceptance stage

on:
  workflow_call:

jobs:
  sandbox-set-up:
    name: Sandbox set up

    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Sandbox set up
      infraRepoName: nhs-notify-iam-webauth
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-deploy-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-iam-dev
      targetComponent: sandbox
      terraformAction: apply

  acceptance-tests:
    name: Acceptance tests
    needs: sandbox-set-up

    permissions:
      id-token: write
      contents: read

    # Calls out to the nhs-notify-internal repo.
    # The nhs-notify-internal repo will run the tests
    # setup in ./.github/actions/acceptance-tests/action.yaml
    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Acceptance tests
      infraRepoName: nhs-notify-iam-webauth
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-acceptance-tests-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-iam-dev
      targetComponent: sandbox

  sandbox-tear-down:
    name: Sandbox tear down
    needs: acceptance-tests
    if: always()

    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Sandbox tear down
      infraRepoName: nhs-notify-iam-webauth
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-deploy-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-iam-dev
      targetComponent: sandbox
      terraformAction: destroy
