name: "Build stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  artefact-jekyll-docs:
    name: "Build Docs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Build docs"
        uses: ./.github/actions/build-docs
        with:
          version: "${{ inputs.version }}"
  artefact-terraform:
    name: "Package Terraform"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Upload artifact"
        uses: ./.github/actions/package-terraform
        with:
          version: "${{ inputs.version }}"
  artefact-n:
    name: "Artefact n"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Build artefact n"
        run: |
          echo "Building artefact n ..."
      - name: "Check artefact n"
        run: |
          echo "Checking artefact n ..."
      - name: "Upload artefact n"
        run: |
          echo "Uploading artefact n ..."
          # TODO: Use either action/cache or action/upload-artifact
